# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Sean Orfila
tagline:          'Interwebz Extraordiarre'
description:      'Frontend Development, UI/UX, Design && other musings totally unrelated to software development.'
url:              https://seandogg.github.io
baseurl:          /

author:
  name:           'Sean Orfila'
  url:            https://twitter.com/seanSince82

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://seandogg.github.io
